// Mocks generated by Mockito 5.4.6 from annotations
// in sivi_chat/test/unit/chat_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sivi_chat/services/api_service.dart' as _i2;
import 'package:sivi_chat/services/chat_service.dart' as _i4;
import 'package:sivi_chat/services/uuid_service.dart' as _i5;
import 'package:stacked_services/src/snackbar/snackbar_config.dart' as _i8;
import 'package:stacked_services/src/snackbar/snackbar_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<dynamic, dynamic>> getChatResponse(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#getChatResponse, [message]),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i4.ChatService {
  MockChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> get chats =>
      (super.noSuchMethod(
            Invocation.getter(#chats),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  Map<String, List<Map<dynamic, dynamic>>> get chatMessages =>
      (super.noSuchMethod(
            Invocation.getter(#chatMessages),
            returnValue: <String, List<Map<dynamic, dynamic>>>{},
          )
          as Map<String, List<Map<dynamic, dynamic>>>);

  @override
  List<Map<dynamic, dynamic>> getMessagesForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesForUser, [userId]),
            returnValue: <Map<dynamic, dynamic>>[],
          )
          as List<Map<dynamic, dynamic>>);

  @override
  void addMessageToChat(String? userId, Map<dynamic, dynamic>? message) =>
      super.noSuchMethod(
        Invocation.method(#addMessageToChat, [userId, message]),
        returnValueForMissingStub: null,
      );

  @override
  void setMessagesForChat(
    String? userId,
    List<Map<dynamic, dynamic>>? messages,
  ) => super.noSuchMethod(
    Invocation.method(#setMessagesForChat, [userId, messages]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic>? getChatForUser(String? userId) =>
      (super.noSuchMethod(Invocation.method(#getChatForUser, [userId]))
          as Map<String, dynamic>?);
}

/// A class which mocks [UuidService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUuidService extends _i1.Mock implements _i5.UuidService {
  MockUuidService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getRandomUuid() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomUuid, []),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getRandomUuid, []),
            ),
          )
          as String);
}

/// A class which mocks [SnackbarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnackbarService extends _i1.Mock implements _i7.SnackbarService {
  MockSnackbarService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSnackbarOpen =>
      (super.noSuchMethod(
            Invocation.getter(#isSnackbarOpen),
            returnValue: false,
          )
          as bool);

  @override
  void registerSnackbarConfig(_i8.SnackbarConfig? config) => super.noSuchMethod(
    Invocation.method(#registerSnackbarConfig, [config]),
    returnValueForMissingStub: null,
  );

  @override
  void registerCustomMainButtonBuilder({
    dynamic variant,
    _i9.Widget Function(String?, Function?)? builder,
  }) => super.noSuchMethod(
    Invocation.method(#registerCustomMainButtonBuilder, [], {
      #variant: variant,
      #builder: builder,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void registerCustomSnackbarConfig({
    required dynamic variant,
    _i8.SnackbarConfig? config,
    _i8.SnackbarConfig Function()? configBuilder,
  }) => super.noSuchMethod(
    Invocation.method(#registerCustomSnackbarConfig, [], {
      #variant: variant,
      #config: config,
      #configBuilder: configBuilder,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void showSnackbar({
    String? title = '',
    required String? message,
    dynamic Function(dynamic)? onTap,
    Duration? duration,
    String? mainButtonTitle,
    void Function()? onMainButtonTapped,
  }) => super.noSuchMethod(
    Invocation.method(#showSnackbar, [], {
      #title: title,
      #message: message,
      #onTap: onTap,
      #duration: duration,
      #mainButtonTitle: mainButtonTitle,
      #onMainButtonTapped: onMainButtonTapped,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<dynamic>? showCustomSnackBar({
    required String? message,
    _i9.TextStyle? messageTextStyle,
    required dynamic variant,
    String? title,
    _i9.TextStyle? titleTextStyle,
    String? mainButtonTitle,
    _i9.ButtonStyle? mainButtonStyle,
    void Function()? onMainButtonTapped,
    Function? onTap,
    Duration? duration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showCustomSnackBar, [], {
              #message: message,
              #messageTextStyle: messageTextStyle,
              #variant: variant,
              #title: title,
              #titleTextStyle: titleTextStyle,
              #mainButtonTitle: mainButtonTitle,
              #mainButtonStyle: mainButtonStyle,
              #onMainButtonTapped: onMainButtonTapped,
              #onTap: onTap,
              #duration: duration,
            }),
          )
          as _i3.Future<dynamic>?);

  @override
  _i3.Future<void> closeSnackbar() =>
      (super.noSuchMethod(
            Invocation.method(#closeSnackbar, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
